name: CI/ CD pipeline
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Build docker Image
      run: docker build -t janiehein/flask-app:latest  .

    - name: login into docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push to docker hub
      run: docker push janiehein/flask-app:latest